### ISSUE TITLE
Upstreaming?

### ISSUE THREAD

**Issue by khaledhosny** [centricular/harfbuzz#5]
I’d like to have the meson build system in upstream HarfBuzz (my not so extensive testing shows that it is good enough to be upstreamed), do you have any blockers?

**Comment by tp-m** [comment]
Not really, I think it's just going over everything and comparing installed files and such - i.e. some sanity checking.

I think @meh was going to do this in the near future.

**Comment by tp-m** [comment]
The only blocker I was aware of is https://github.com/mesonbuild/meson/issues/3688 which has been fixed, and I have added g-i support earlier today.

Should probably also rebase on top of master, it looks like we're two micro-releases behind.

**Comment by khaledhosny** [comment]
I think you are much more than two micro releases, there was a new major release last month. I can give rebasing on master a try.

**Comment by khaledhosny** [comment]
I rebased and fixed the build, but some tests are failing now. Will check in the morning.

**Comment by khaledhosny** [comment]
I think I’m done with the rebase, how do you want to get it (apparently a pull request wouldn’t work).

**Comment by tp-m** [comment]
If you point me to a branch I can force-push it.

Alternatively, of course also feel free to submit or push it directly to harfbuzz yourself, and if anything else comes up we'll fix it afterwards then.

**Comment by khaledhosny** [comment]
Branch here https://github.com/khaledhosny/harfbuzz/tree/meson, I appreciate if you can have a look and send HarfBuzz PR when ready (I only tested on Linux).

**Comment by tp-m** [comment]
Looks fine at first glance - only thing that doesn't look right is the addition of all those `.hh` files  to the various `_sources` variables. In Meson that should not be needed, it will figure out the header file dependencies automatically from the `.c` and `.cc` source files (via the compiler).

They either should go into one of the `_headers` variables (if they need to be installed or passed to gobject-introspection) or be omitted entirely.

**Comment by khaledhosny** [comment]
I was getting various linking errors without this, these `.hh` are internal headers and often contain implantation code not just declarations, so it looked like they qualify as sources not headers. But feel free to change the build files as you see fit.

**Comment by tp-m** [comment]
I'm a bit stuck at the moment, because the build is broken with MSVC (see https://github.com/harfbuzz/harfbuzz/issues/1374) but it doesn't look like you guys are going to fix it, so I now have to first figure out what's broken there and how to fix it before I can make sure the meson build files are correct and up-to-date for MSVC.

**Comment by khaledhosny** [comment]
That is only with very old MSVC, master is building fine on Visual Studio 2014: https://ci.appveyor.com/project/harfbuzz/harfbuzz

**Comment by tp-m** [comment]
Alright, thanks, that's good to know. Will poke at it some more then (using vs2015 here).

**Comment by ebraminio** [comment]
Didn't read the whole thread but we made some progress on supporting older compilers, have a look.

**Comment by tp-m** [comment]
Thanks for the effort and follow-up. I was testing with vs2015 so not sure it's the same issue, but haven't had a chance to try the cmake build to double-check yet either. I'm 75% sure it's a meson build file issue in my case, maybe a missing c++ std specifier or somesuch. Will rebase and double check, thanks.

**Comment by tp-m** [comment]
Just for other people's reference, the PR for this is here: https://github.com/harfbuzz/harfbuzz/pull/1437 (probably needs some rebasing/updating again though, hard to keep up)
