### ISSUE TITLE
Feature request: rebase to harfbuzz 2.x

### ISSUE THREAD

**Issue by boxerab** [centricular/harfbuzz#6]
I am trying to build Pango with meson, and it requires Harfbuzz version >= 2.0.0

**Comment by tp-m** [comment]
You can try this branch here: https://github.com/tp-m/harfbuzz/tree/meson-rebased

There's a [PR upstream for the Meson port](https://github.com/harfbuzz/harfbuzz/pull/1437) so I think I'll close this :)

**Comment by boxerab** [comment]
Thanks, @tpm. I took that branch and rebased with Harfbuzz master.

https://github.com/boxerab/harfbuzz/tree/meson

This builds Harfbuzz 2.2
